"""empty message

Revision ID: 787d76d871f5
Revises: 8ce1e3dbc428
Create Date: 2025-10-17 09:11:43.709940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787d76d871f5'
down_revision = '8ce1e3dbc428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###
