"""empty message

Revision ID: 7cf5bb99ca8b
Revises: 880e8c9bd5ff
Create Date: 2025-10-21 21:39:22.846799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf5bb99ca8b'
down_revision = '880e8c9bd5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_prod_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('prod_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('order_prod_id_fkey', type_='foreignkey')
        batch_op.drop_column('prod_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('prod_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('order_prod_id_fkey', 'product', ['prod_id'], ['id'])
        batch_op.create_foreign_key('order_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('prod_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favorite_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_prod_id_fkey', 'product', ['prod_id'], ['id'])

    op.drop_table('order_item')
    # ### end Alembic commands ###
